# Generated by Django 4.0.6 on 2022-11-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_id', models.CharField(max_length=300, null=True)),
                ('name', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
