# Generated by Django 4.0.6 on 2022-11-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_variables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variables',
            new_name='Variable',
        ),
    ]
