# Generated by Django 4.0.6 on 2022-12-17 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('variable', models.TextField()),
                ('country', models.TextField()),
                ('initial_date', models.DateField()),
                ('final_date', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
