# Generated by Django 4.0.6 on 2022-12-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_varmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varmodel',
            name='final_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='varmodel',
            name='initial_date',
            field=models.TextField(),
        ),
    ]
