# Generated by Django 4.0.6 on 2022-12-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_country_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='varmodel',
            name='json_data',
            field=models.JSONField(default='{}'),
        ),
    ]
