# Generated by Django 4.0.6 on 2022-12-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_varmodel_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='varmodel',
            name='final_date',
        ),
        migrations.RemoveField(
            model_name='varmodel',
            name='initial_date',
        ),
        migrations.RemoveField(
            model_name='varmodel',
            name='variable',
        ),
    ]
